# Generated by Django 3.0.5 on 2021-05-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='franchiseuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='franchiseuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='franchiseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='franchiseuser',
            name='mobile_no',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
